// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYYMqdVJQBSrHH5gL-xtfdvp57tWyk5m4',
    appId: '1:899519615594:web:2a4678c06db61a95047013',
    messagingSenderId: '899519615594',
    projectId: 'okuyorum-6801b',
    authDomain: 'okuyorum-6801b.firebaseapp.com',
    storageBucket: 'okuyorum-6801b.firebasestorage.app',
    measurementId: 'G-6SH1WHZEYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2hXcUkU3R4Yb7pv9EIAR6cUUKg9aj0UA',
    appId: '1:899519615594:android:71f7418ff6c073b2047013',
    messagingSenderId: '899519615594',
    projectId: 'okuyorum-6801b',
    storageBucket: 'okuyorum-6801b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz--XwxAkLIaQmZAYrhZxAv5haZcpp08k',
    appId: '1:899519615594:ios:8a7046f9bf7cd8fd047013',
    messagingSenderId: '899519615594',
    projectId: 'okuyorum-6801b',
    storageBucket: 'okuyorum-6801b.firebasestorage.app',
    iosBundleId: 'com.nisa.okuyorum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz--XwxAkLIaQmZAYrhZxAv5haZcpp08k',
    appId: '1:899519615594:ios:8a7046f9bf7cd8fd047013',
    messagingSenderId: '899519615594',
    projectId: 'okuyorum-6801b',
    storageBucket: 'okuyorum-6801b.firebasestorage.app',
    iosBundleId: 'com.nisa.okuyorum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYYMqdVJQBSrHH5gL-xtfdvp57tWyk5m4',
    appId: '1:899519615594:web:9683e0ed03c9e915047013',
    messagingSenderId: '899519615594',
    projectId: 'okuyorum-6801b',
    authDomain: 'okuyorum-6801b.firebaseapp.com',
    storageBucket: 'okuyorum-6801b.firebasestorage.app',
    measurementId: 'G-BSHEP4HCN7',
  );
}
